[package]
name = "color-shredder"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
web-sys = { version = "0.3", features = ["CanvasRenderingContext2d", "HtmlCanvasElement", "ImageData"] }
wasm-bindgen = "0.2"